apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.name" . }}
  labels:
    app: {{ include "backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.openaiSecretName | quote }} 
                  key: {{ .Values.env.openaiSecretKey | quote }}
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: clientSecret
            - name: REDIRECT_URL
              value: {{ .Values.env.redirectUrl | quote }}
            - name: ISSUER_URL
              value: {{ .Values.env.issuerUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
